### PR TITLE
Sentence-case

### LINKED ISSUE #987: Make sure everywhere we use consistent capitalization
Make sure everywhere we use consistent capitalization: only the first word of a sentence, e.g. not “Job List” but “Job list”. Can you give a thorough check to *all* strings?
Everywhere, write PDOS all capital letters (including the default label)

### PR DESCRIPTION
**Pull request by edan-bainglass**
This PR enforces sentence casing throughout the app.

Closes #987

### CODE REVIEW

**Comment by edan-bainglass** [comment]
@superstar54 just review the [last commit](https://github.com/aiidalab/aiidalab-qe/pull/1034/commits/cc6a5bff3897b0cf7953ca96fe3e1b2300d1dcbd)

**Comment by edan-bainglass** [comment]
@superstar54 I'm trying to fix the failed test. Simple enough, just regenerate the summary reference. However, since upgrading to the latest image, I can no longer run tests locally 😞 First I was missing `locate`, which I installed as root via `apt update & apt install locate`. But now I get `FileNotFoundError: 'pg_ctl' could not be found.`

**Comment by edan-bainglass** [comment]
> @superstar54 I'm trying to fix the failed test. Simple enough, just regenerate the summary reference. However, since upgrading to the latest image, I can no longer run tests locally 😞 First I was missing `locate`, which I installed as root via `apt update & apt install locate`. But now I get `FileNotFoundError: 'pg_ctl' could not be found.`

This is an issue with our stack. See [here](https://github.com/aiidalab/aiidalab-docker-stack/pull/383#pullrequestreview-1440255763). For now, switching to the `aiida-core-services` environment allowed me to run the tests.

**Comment by edan-bainglass** [comment]
> > @superstar54 I'm trying to fix the failed test. Simple enough, just regenerate the summary reference. However, since upgrading to the latest image, I can no longer run tests locally 😞 First I was missing `locate`, which I installed as root via `apt update & apt install locate`. But now I get `FileNotFoundError: 'pg_ctl' could not be found.`
> 
> This is an issue with our stack. See [here](https://github.com/aiidalab/aiidalab-docker-stack/pull/383#pullrequestreview-1440255763). For now, switching to the `aiida-core-services` environment allowed me to run the tests.

Also, the solution was not to regenerate. It's just that the test is looking for hard coded strings that this PR changed (made sentence-case). Fixed!

**Comment by edan-bainglass** [comment]
@superstar54 can you please have a quick look once the tests pass? 🙏

**Comment by superstar54** [comment]
> can you please have a quick look once the tests pass?

The test failed. Seems need to change "From Example" to "From example"?

**Review by superstar54 — APPROVED** [review]
Hi @edan-bainglass , LGTM! I approved. Please merge when the tests pass.

**Comment by edan-bainglass** [comment]
@superstar54 the docker build is now consistently failing with a timeout on `test_qe_app_select_silicon_and_confirm`. Can you have a look? Likely related to your `From examples` changes. I'll merge this one though, as it is unrelated.

**Comment by edan-bainglass** [comment]
> @superstar54 the docker build is now consistently failing with a timeout on `test_qe_app_select_silicon_and_confirm`. Can you have a look? Likely related to your `From examples` changes. I'll merge this one though, as it is unrelated.

Ah, it IS this PR that is the cause of the failure. The test is looking for "From Examples", but this PR made it "From examples", so there we go. Okay, will fix in another PR.

**Pull request merged**
