### PR TITLE
Updating bandspdos widget

### PR DESCRIPTION
**Pull request by AndresOrtegaGuerrero**
This PR address #821 #812 

The PR involve these changes

- [x]  Improve Default PDOS zoom/scaling based on values
- [x]  Modification of Update button to Apply Selection
- [x]  Interactive re-plotting after changes in the Dropdown Menus
- [x] Include a short description of the plot being interactive
- [x] Add a placeholder for the Selection atom widget 
- [x] Orbital contribution are separated.

image

image

Here a test with Tot_magnetization, 

image

image

Test Au, using labels in StructureData , 

image

### CODE REVIEW

**Comment by AndresOrtegaGuerrero** [comment]
@t-reents at the moment I can't add you as a reviewer, but please have a look , and give us your review

**Comment by AndresOrtegaGuerrero** [comment]
The tests (pictures) were updated displaying the appropriated selection of orbitals

**Review by cpignedoli — APPROVED** [review]
Tested on my local instance,for me works

**Review by t-reents — APPROVED** [review]
LGTM! Thanks @AndresOrtegaGuerrero

**Review by edan-bainglass — APPROVED** [review]
Go ahead @AndresOrtegaGuerrero. We'll discuss later how to best sync this up against the MC implementation.

**Pull request merged**
