### PR TITLE
Autoupdate .pre-commit-config.yaml quarterly

### PR DESCRIPTION
**Pull request by danielhollas**
Per discussion in https://github.com/aiidalab/aiidalab-widgets-base/pull/424

@unkcpz @yakutovicha (don't have privileges to ask for reviewers on this repo)

### CODE REVIEW

**Comment by danielhollas** [comment]
@unkcpz the test is failing at

```
>       confirm_button = driver.find_element(By.XPATH, "//button[text()='Confirm']")
```

Probably you need to port the `final_screenshot` fixture here to debug this.

**Comment by unkcpz** [comment]
> Probably you need to port the final_screenshot fixture here to debug this.

Sure. But since we take two screenshots in this tast case, we have to use the regular try..catch to get the screenshot, correct?
I also have evidence that the failed test was caused by the waiting time after the click at the confirm button not long enough. If you have a look at the screenshot you'll find the notebook is in loading. It stuck at the front page or the confirm button is not light up yet. 
Same issue for https://github.com/aiidalab/aiidalab-qe/pull/342 and tests pass by increase the wait time.

**Comment by danielhollas** [comment]
I don't thino you nedled try..except. the important thing is to have at
least one screenshot when the test fails, so you can use the fixture for
the final screenshot, and keep the first one as is.

Dne čt 26. 1. 2023 9:06 dop. uživatel Jusong Yu ***@***.***>
napsal:

**Comment by unkcpz** [comment]
@danielhollas thanks for update the PR. I open an issue so I don't forget to implement that next month.

**Review by unkcpz — APPROVED** [review]
Since all tests pass, I approve it.

**Pull request merged**
