### PR TITLE
removing force_parity from create_kpoints_from_distance

### PR DESCRIPTION
**Pull request by AndresOrtegaGuerrero**
This allows the app to follow the same logic of aiida-quantumespresso plugin, therefore displaying the final kpoint mesh as in the calculation

### CODE REVIEW

**Comment by unkcpz** [comment]
> This allows the app to follow the same logic of aiida-quantumespresso plugin

Hi @AndresOrtegaGuerrero, what you mean of "same logic"? I look at the function in `aiida-quantumespresso`, but it has no default value defined for `force_parity`. https://github.com/aiidateam/aiida-quantumespresso/blob/c44faadc7c11f7118290cf1b7affe49313bd4467/src/aiida_quantumespresso/calculations/functions/create_kpoints_from_distance.py#L7

**Comment by AndresOrtegaGuerrero** [comment]
@unkcpz in the base workchain, https://github.com/aiidateam/aiida-quantumespresso/blob/main/src/aiida_quantumespresso/workflows/pw/base.py#L7 

thats why the value we display is not necessarily the one is being used in the calculations since it should be force_parity false

**Comment by unkcpz** [comment]
Ah, I see, it is https://github.com/aiidateam/aiida-quantumespresso/blob/b517686df8cd33765ef12cbf430620ea8e94f137/src/aiida_quantumespresso/workflows/pw/base.py#L278 😉

**Review by unkcpz — APPROVED** [review]
Thanks!

**Pull request merged**
