### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by edan-bainglass**
Per request, changing logo to "The AiiDAlab Quantum ESPRESSO App"

### CODE REVIEW

**Comment by superstar54** [comment]
@edan-bainglass thanks for the update. Do you know why the text on the SVG image overlaps? At lease on my browser and computer.

**Comment by edan-bainglass** [comment]
Updated the logo to handle light and dark modes. However, the `pydata-sphinx-theme` built-in `dark-light` class does not seem to work when applied to the icon on the front page. It works when I build the docs locally, just not on the remote for some reason.

**Comment by edan-bainglass** [comment]
@superstar54 can we merge this?

**Comment by superstar54** [comment]
> @superstar54 can we merge this?

I really want to merge this. However, I still see strange logo in my computer. 

Screenshot from 2024-04-30 17-10-01


@AndresOrtegaGuerrero , could you check the logo in the page
https://aiidalab-qe--635.org.readthedocs.build/

If no problem in your computer, we can merge this PR.

**Comment by AndresOrtegaGuerrero** [comment]
@superstar54 Is the same for me 
image

@edan-bainglass  Do you know how we can fix this ?

**Comment by edan-bainglass** [comment]
Probably need to stop using SVG files I suppose. PNG versions shouldn't have this problem. I'll look into it tomorrow.

**Comment by edan-bainglass** [comment]
Switched to png files. Tested on Windows and Linux. @AndresOrtegaGuerrero let me know how it looks on your Mac.

**Review by superstar54 — APPROVED** [review]
thanks, LGTM!

**Review by AndresOrtegaGuerrero — APPROVED** [review]
LGTM! Thank you Edan

**Comment by edan-bainglass** [comment]
@mbercx is the required amd64 test not running somehow connected to your office machine? Is it down again? 😞

**Pull request merged**
