### PR TITLE
changing the labels of periodicity widget

### PR DESCRIPTION
**Pull request by AndresOrtegaGuerrero**
This PR changes the labels of the periodicity options widget as the following 

image

### CODE REVIEW

**Comment by cpignedoli** [comment]
We suggest the following labels:
3D (bulk)
2D (surfaces, slabs, ...) [NOTE: the non-periodic direction must be the third lattice vector, AND be along z]
1D (wires) [NOTE: the periodic direction must be the first lattice vector, AND be along x]
0D (molecules)

**Review by cpignedoli — COMMENTED** [review]
Hi @AndresOrtegaGuerrero , were there follow up discussions to move slightly away from
https://github.com/aiidalab/aiidalab-qe/pull/933 ?
otherwise I would stick to what was decided there if space allows

**Comment by cpignedoli** [comment]
I would keep (surfaces, slabs, ...) to leave it open to other cases we do not mention.

**Comment by AndresOrtegaGuerrero** [comment]
image

**Comment by cpignedoli** [comment]
OK from my side. Automatic detection of periodicity using the function suggested by @giovannipizzi (P1 https://github.com/orgs/aiidalab/projects/17/views/1?pane=issue&itemId=88010088) will follow as a separate PR

**Comment by AndresOrtegaGuerrero** [comment]
image

**Comment by AndresOrtegaGuerrero** [comment]
@cpignedoli @giovannipizzi Like this figure above is correct ?

**Comment by AndresOrtegaGuerrero** [comment]
image

**Review by cpignedoli — APPROVED** [review]
Reflects what we discussed so far.

**Comment by giovannipizzi** [comment]
Just to be sure, *both* requirements are needed (both being the 3rd lattice vector, *and* being along z), right?

OK to keep as it is and if people complain, we make it even clearer

**Pull request merged**
