### PR TITLE
Add clean-up button to control the remote work directory clean

### LINKED ISSUE #370: Clean the remote workdir as default and provide checkbox for not clean up
**Is your feature request related to a problem? Please describe.**
In the THEOS testing server, the storage space of active user increased dramatically. The issue comes from that the calculation folder is not cleaned up if run in localhost. 

**Describe the solution you'd like**
Clean up the remote workdir if the calculation finished successfully, provide the widget to tick the option to turn off clean up.

### PR DESCRIPTION
**Pull request by unkcpz**
fixes #370

### CODE REVIEW

**Review by mikibonacci — COMMENTED** [review]
Hi jason, is it intended to leave some space between the checkbox and the description?


Screenshot from 2023-10-09 11-41-17

**Review by mikibonacci — APPROVED** [review]

**Comment by unkcpz** [comment]
> Hi jason, is it intended to leave some space between the checkbox and the description?

Good point, I didn't expect the space are so large. I intended to use the `px` instead of the `%`. I polished it a bit. We need anyway go though all the layout and make everything look compact, but that is a task for the future.

**Comment by AndresOrtegaGuerrero** [comment]
@mikibonacci By default the check box is always on ? This could be problematic if an user missed this and wanted to do postprocessing with some files not saved

**Comment by unkcpz** [comment]
> This could be problematic if an user missed this and wanted to do postprocessing with some files not saved

Then, it will be an "advanced" user and he is supposed to go to the advance setting and un-tick it I assume?

**Comment by unkcpz** [comment]
As we discussed in the last AiiDAlab meeting, we agree that the workchain should not be cleaned by default. I'll open a PR for it after.

**Pull request merged**
