### PR TITLE
Redesign summary view

### PR DESCRIPTION
**Pull request by edan-bainglass**
This PR is one in several that will address #1042

Here, I introduce a bullet list alternative format for the summary report (no actual bullets). The format is defined in `qeapp.yml` as `summary_format: list` and can be overridden by the user in a config file (see #1007 for info regarding file). `summary_format` takes `list` or `table`.

I also adjust the style such that the data download widget is to the right of the summary instead of below. This is true for either selected format.

Lastly, I add "Workflow properties" and "Structure properties" sections to the summary.

---

image

image

### CODE REVIEW

**Comment by edan-bainglass** [comment]
If anyone has an older container (with an older AiiDA version, say, 2.5ish), can you please verify that you still get the notification regarding the unavailability of the raw data download feature?

**Comment by AndresOrtegaGuerrero** [comment]
why dont you try with `from IPython.core.display import HTML` and create the tables , like that you have more flexibility in the appearance. 

Also since the tab of picking the settings was Basic settings, you should keep the same instead of using Main settings

**Comment by edan-bainglass** [comment]
> why dont you try with `from IPython.core.display import HTML` and create the tables , like that you have more flexibility in the appearance.

No idea what you're referring to 😅

> Also since the tab of picking the settings was Basic settings, you should keep the same instead of using Main settings

This was a specific request by Giovanni. See issue.

**Comment by AndresOrtegaGuerrero** [comment]
> > why dont you try with `from IPython.core.display import HTML` and create the tables , like that you have more flexibility in the appearance.
> 
> No idea what you're referring to 😅

You can make an HTML object and create a table and to display it , it has better visuals than the ipywidget.HTML. 

The table gave this kind of separation that was nice , plus a highlight , but indeed they were to big the cell size. 

> > Also since the tab of picking the settings was Basic settings, you should keep the same instead of using Main settings
> 
> This was a specific request by Giovanni. See issue.
Ok , then we should keep it consistent in the configuration step , and name it main settings as well (instead of basic)

**Comment by AndresOrtegaGuerrero** [comment]
@edan-bainglass I can confirm you that the notification for aiida 2.5 works 
image

**Comment by edan-bainglass** [comment]
Thanks @AndresOrtegaGuerrero 🙏

**Comment by edan-bainglass** [comment]
@giovannipizzi @cpignedoli alternative...

image

Both `list` and `table` are now valid choices for a new `summary_format` configuration key, which thanks to #1007, is now user-configurable. Currently defaulting to `list`, though the table view is quite clean in my opinion (suggested by @AndresOrtegaGuerrero).

Also, "Main settings" is inconsistent to "Basic settings". Best we uniform this. Do you agree, and if so, preference?

**Comment by giovannipizzi** [comment]
Thanks! Both are good, table is OK as the dark color is not too dark/prominent. But as the list might get longer, maybe the list is OK. I agree with uniforming basic/main,maybe "main" is better but both are are ok.

**Comment by edan-bainglass** [comment]
> Thanks! Both are good, table is OK as the dark color is not too dark/prominent. But as the list might get longer, maybe the list is OK. I agree with uniforming basic/main,maybe "main" is better but both are are ok.

Okay then. Leaving `list` as the default. And I think I'll stick to "basic".

**Comment by edan-bainglass** [comment]
Adding more info requested in #1042

image

and

image

**Comment by AndresOrtegaGuerrero** [comment]
I would suggest omitting the "Workflow Properties" section. If the concern was that the current display is distracting, this version is even more so.

Displaying the creation and modification times, as well as the UUID, seems unnecessary. Also, isn't the PK number already shown at the top?

Instead of adding a separate section, I think we could include the PK, label, and description just above the "Workflow completed successfully" message.

image

**Comment by AndresOrtegaGuerrero** [comment]
And we rather have the Structure "properties" in the results tab Initial Structure 

image

**Comment by edan-bainglass** [comment]
@AndresOrtegaGuerrero could you please review once more? 🙏

**Comment by AndresOrtegaGuerrero** [comment]
@edan-bainglass Thank you! In my test everything works. I did notice an issue I mentioned in #1045, where we sometimes fail to indicate whether the full workflow completed successfully. However, I’m thinking this might not be the right place to address it—what do you think?

**Comment by AndresOrtegaGuerrero** [comment]
Just dont forget to solve the conflict

**Review by AndresOrtegaGuerrero — APPROVED** [review]
LGTM! Thank you @edan-bainglass

**Comment by AndresOrtegaGuerrero** [comment]
@edan-bainglass It just crossed my mind now, should we report the properties computed ?

**Comment by edan-bainglass** [comment]
> @edan-bainglass Thank you! In my test everything works. I did notice an issue I mentioned in #1045, where we sometimes fail to indicate whether the full workflow completed successfully. However, I’m thinking this might not be the right place to address it—what do you think?

Indeed, unrelated. Thanks for opening the issue.

**Comment by edan-bainglass** [comment]
> @edan-bainglass It just crossed my mind now, should we report the properties computed ? 

I suppose so? Doesn't hurt. I'll add it 👍

**Comment by edan-bainglass** [comment]
> > @edan-bainglass It just crossed my mind now, should we report the properties computed ?
> 
> I suppose so? Doesn't hurt. I'll add it 👍

@AndresOrtegaGuerrero not sure where and how to best represent the computed properties. For now, I'll merge without it. Let's discuss and PR this later.

**Pull request merged**
