### PR TITLE
Features/warning long calc

### PR DESCRIPTION
**Pull request by mikibonacci**
This fixes https://github.com/aiidalab/aiidalab-qe/issues/816.

### CODE REVIEW

**Comment by mikibonacci** [comment]
Hi @AndresOrtegaGuerrero  and @superstar54 , the PR is ready for review. 

In the submission step, I added (completed what I already found there) checks for: number of sites (lower than 10 is safe), cell volume (lower then 1000 A^3 is safe) and number of cpus (lower than 4 is not safe for big systems - see previous checks and Figure 1 - higher than 1 in localhost ask for checks, see Figure 2)
Figure 1 (similar warning even if not in localhost - see the code) is:
Screenshot 2024-10-07 at 16 30 53

Figure 2 is:
Screenshot 2024-10-07 at 16 32 10

**Comment by AndresOrtegaGuerrero** [comment]
you have some issues in the tests, @mikibonacci is it possible to create a test , to check this logic ?

**Comment by mikibonacci** [comment]
Hi @AndresOrtegaGuerrero, yeah will put some test, should be possible

**Comment by mikibonacci** [comment]
Hi @AndresOrtegaGuerrero , I updated the descriptions. For the tests: I added the testing for the localhost part, not for the non-localhost (I am not sure how to do it, as we should load an external code...). Let me know if you have some ideas on how to do it, or if we can go like this.

thanks!

**Review by AndresOrtegaGuerrero — APPROVED** [review]
LGTM! Thank you Miki

**Pull request merged**
