### PR TITLE
Bump aiidalab-widgets-base to version 2.1.0b0

### PR DESCRIPTION
**Pull request by AndresOrtegaGuerrero**
This PR update aiidalab-widgets-base to allow the app to visualize the supercell implementation from @superstar54

### CODE REVIEW

**Comment by unkcpz** [comment]
Thanks! I was about to do this 1 hour ago but was distracted by something else.

**Review by unkcpz — APPROVED** [review]
Let's wait the tests and we can merge it and release another beta version of the app.

**Comment by AndresOrtegaGuerrero** [comment]
> Let's wait the tests and we can merge it and release another beta version of the app.

Maybe lets solve the issue of the 1D and 2D bands problem and then you release it ?

**Comment by unkcpz** [comment]
> Maybe lets solve the issue of the 1D and 2D bands problem and then you release it ?

Sure!

**Pull request merged**
