### PR TITLE
Fix: Pure relaxation fails

### PR DESCRIPTION
**Pull request by unkcpz**
This is a quick fix for #259, but when I look at the code, I find there could be some problem with the parameters not properly set from `qeapp.yaml`. 
So if it is not extremely emergence, I'll dig into it more and update this PR. What you thought? @csadorf

### CODE REVIEW

**Comment by csadorf** [comment]
> This is a quick fix for #259, but when I look at the code, I find there could be some problem with the parameters not properly set from `qeapp.yaml`. So if it is not extremely emergence, I'll dig into it more and update this PR. What you thought? @csadorf

I would recommend to release the fix immediately since this bug brakes a core function of the app. As a next step I would recommend to

1. Identify what caused this bug.
2. Implement tests that would catch the issue in the future.

Were you able to reproduce the problem and confirm that this fix solves it or should I test it myself?

**Comment by unkcpz** [comment]
I mess up my local qeapp aiidalab environment, need some time to fix and test it. I reproduce issue will online aiidalab but can not check if this PR fixes that.

**Comment by unkcpz** [comment]
> Implement tests that would catch the issue in the future.

How are we going to add a test for this? We literally have zero tests for anything of this app.

**Comment by csadorf** [comment]
> > Implement tests that would catch the issue in the future.
> 
> How are we going to add a test for this? We literally have zero tests for anything of this app.

[That is not true](https://github.com/aiidalab/aiidalab-qe/blob/master/tests/test_qe_app.py), they are just not automatically executed at the moment. It is not too hard to implement additional tests with selenium.

**Comment by unkcpz** [comment]
> [That is not true](https://github.com/aiidalab/aiidalab-qe/blob/master/tests/test_qe_app.py), they are just not automatically executed at the moment. It is not too hard to implement additional tests with selenium.

I mean the smoke test is now turned off which will actually trigger the test. Could you have a look at it if you get the time?

**Comment by csadorf** [comment]
> I mean the smoke test is now turned off which will actually trigger the test. Could you have a look at it if you get the time?

Sure, can you create an issue, please?

**Comment by unkcpz** [comment]
There is an issue for that https://github.com/aiidalab/aiidalab-qe/issues/205. I add it to the roadmap.

**Pull request merged**
