### PR TITLE
Add `QeAppWorkChain`

### PR DESCRIPTION
**Pull request by mbercx**
Add first version of the `QeAppWorkChain`, which is a wrapper work chain
for the `PwRelaxWorkChain`, `PwBandsWorkChain`, and the `PdosWorkChain`.
By combining the three work chains into one, it makes it easier to
obtain a pre-populated builder using the `get_builder_from_protocol`
method and re-use results inside the work chain.

### CODE REVIEW

**Comment by csadorf** [comment]
@yakutovicha Since you are collaborating on this branch, please do not use force-pushes. If you need to fix up a commit, please use git's `--fixup` feature.

**Comment by csadorf** [comment]
@yakutovicha Can we merge this PR the second it's functional and then make any further cosmetic changes in separate PRs?

**Comment by yakutovicha** [comment]
> @yakutovicha Can we merge this PR the second it's functional and then make any further cosmetic changes in separate PRs?

@csadorf yes, I am working on the changes we discussed yesterday. Didn't manage to implement them yet.

**Comment by csadorf** [comment]
> > @yakutovicha Can we merge this PR the second it's functional and then make any further cosmetic changes in separate PRs?
> 
> @csadorf yes, I am working on the changes we discussed yesterday. Didn't manage to implement them yet.

Sorry, did not mean to rush you, but instead emphasize that this PR should not contain *any* cosmetic work but should focus entirely on function.

**Comment by yakutovicha** [comment]
> Sorry, did not mean to rush you, but instead emphasize that this PR should not contain _any_ cosmetic work but should focus entirely on function.

sure, I am focusing on functionality.

**Comment by yakutovicha** [comment]
@csadorf I think I am done with my changes. Things seem to work fine now. Can you take care of fixing git issues and merging the PR?

**Comment by csadorf** [comment]
> @csadorf I think I am done with my changes. Things seem to work fine now. Can you take care of fixing git issues and merging the PR?

Yes, will do! 👍

**Comment by csadorf** [comment]
@yakutovicha I believe that I resolved all merge conflicts correctly, however I was not able to run the example. The `verdi process report` yields:
```
[...]
aiida.common.exceptions.MissingEntryPointError: Entry point 'quantumespresso.pdos' not found in group 'aiida.workflows'. Try running `reentry scan` to update the entry point cache.
```
I ran `reentry scan`, but it did not fix the problem.

**Comment by yakutovicha** [comment]
> I ran `reentry scan`, but it did not fix the problem.

maybe you have the qe plugin also installed in the ~/bin/ folder. Try to uninstall it as `aiida` user and re-run reentry

**Comment by csadorf** [comment]
For the record, it appears that there was some kind "zombie" daemon with an outdated reentry cache that I was not able to restart with `verdi daemon restart`. I restarted the whole server and now the daemon is picking up the work chain.

**Comment by csadorf** [comment]
@yakutovicha I am going to assume that you will further revise the interface and I am going to start working on the _work chain node_ viewer, correct?

**Comment by yakutovicha** [comment]
> @yakutovicha I am going to assume that you will further revise the interface and I am going to start working on the _work chain node_ viewer, correct?

sure, I just need suggestions from you guys on how to better place the elements.

**Comment by csadorf** [comment]
> > @yakutovicha I am going to assume that you will further revise the interface and I am going to start working on the _work chain node_ viewer, correct?
> 
> sure, I just need suggestions from you guys on how to better place the elements.

@yakutovicha I've created a mock-up of how I would imagine step 2 to look like:
Screenshot 2021-03-24 at 19 56 23
I've implemented most of the other tabs as well (see the attached module).
[step2.py.txt](https://github.com/aiidalab/aiidalab-qe/files/6199809/step2.py.txt)

**Comment by yakutovicha** [comment]
> I've implemented most of the other tabs as well (see the attached module).

I like it! I would probably rename "Configure codes" with "Select codes" but the rest looks good to me.

**Comment by csadorf** [comment]
> > I've implemented most of the other tabs as well (see the attached module).
> 
> I like it! I would probably rename "Configure codes" with "Select codes" but the rest looks good to me.

Yeah, I guess that's fine. I suggest that you implement a first pass connecting all the various elements so that this is mostly functional and then we can work on the fine-tuning. For example, I would like to show a little icon when there is a tab that requires user intervention, e.g., to inform the user that they need to select a dos code when none is selected, but the dos step is enabled, etc.

**Pull request merged**
