### PR TITLE
Bump quantumespresso plugin to 4.5.0

### PR DESCRIPTION
**Pull request by unkcpz**

### CODE REVIEW

**Comment by AndresOrtegaGuerrero** [comment]
For the #577 , we should wait until https://github.com/aiidateam/aiida-quantumespresso/pull/1007 is merged. Also is covenient for #512

**Comment by danielhollas** [comment]
@unkcpz @superstar54  FYI this update is needed for `aiida-core~=2.5` since earlier version of  `aiida-quantumespresso` depend on pydantic v1.

This is a bit unfortunate, since you're going to have a hard breaking change in the next release --- older releases will only work on older images, while the new v2.5 image will only support the latest release.

**Comment by unkcpz** [comment]
I think pinning to the minor version will do the trick, if the aiida-core in the docker stack < 2.5, the `aiida-quantumespresso==4.4` will be installed, otherwise with install `aiida-quantumespresso==4.5` with pydantic v2.

**Comment by unkcpz** [comment]
Hi @superstar54, can you check why the unit test failed? I don't understand why the `max_iteration` is in the reference test data of data-regression output.

**Comment by superstar54** [comment]
@unkcpz this is introduced in this [commit](https://github.com/rikigigi/aiida-quantumespresso/commit/24148c3067e22d2ed9e130f3175b99a6265727e2) from latest aiida-quantumespresso. I think you can update the reference data to include it.

**Comment by danielhollas** [comment]
> I think pinning to the minor version will do the trick, if the aiida-core in the docker stack < 2.5, the aiida-quantumespresso==4.4 will be installed, otherwise with install aiida-quantumespresso==4.5 with pydantic v2.

Sounds reasonable, I did a couple of quick tests locally to verify different combinations work, e.g.

```console
uv pip install -e . aiida-core==2.5
uv pip install -e . aiida-core==2.4 pydantic~=1.0   # This one installes 4.4 version
uv pip install -e . aiida-core==2.4
```

**Comment by danielhollas** [comment]
> Hi @superstar54, can you check why the unit test failed? I don't understand why the max_iteration is in the reference test data of data-regression output.

Hmm, perhaps to prevent potential breakages in the future, you might want to do 

`aiida-quantumespresso~=4.4,<4.6`

**Comment by unkcpz** [comment]
Blocked by https://github.com/aiidalab/aiidalab-qe/issues/638

**Comment by superstar54** [comment]
@danielhollas @unkcpz ready to go!

**Comment by unkcpz** [comment]
Thanks @superstar54 for the work, but I try not too much optimistic. I bump the aiida-core version in CI to 2.5, hope it passed.

**Comment by unkcpz** [comment]
Nice, tests still all passed after bump aiida-core version in CI matrix. Good to go! This is my PR so I can not approve. @danielhollas can you give it a final check that we didn't miss anything else.

**Review by danielhollas — APPROVED** [review]

**Pull request merged**
