### PR TITLE
run_relax should be used for get pw-parameters

### LINKED ISSUE #318: Does not have an input with link label 'relax' in report widget
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments (optional):

Cobalt -> non-relax -> two properties + moderate

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
~/apps/aiidalab-qe/aiidalab_qe/node_view.py in __init__(self, node, **kwargs)
    520             """
    521         )
--> 522         self.workflows_summary = SummaryView(self.node)
    523 
    524         self.summary_tab = ipw.VBox(children=[self.workflows_summary])

~/apps/aiidalab-qe/aiidalab_qe/node_view.py in __init__(self, wc_node, **kwargs)
    286             return "Yes" if truthy else "No"
    287 
--> 288         report = generate_report_dict(self.wc_node)
    289 
    290         env = Environment()

~/apps/aiidalab-qe/aiidalab_qe/report.py in generate_report_dict(qeapp_wc)
    132 def generate_report_dict(qeapp_wc):
    133     """Generate a dictionary for reporting the inputs for the `QeAppWorkChain`"""
--> 134     return dict(_generate_report_dict(qeapp_wc))
    135 
    136 

~/apps/aiidalab-qe/aiidalab_qe/report.py in _generate_report_dict(qeapp_wc)
    100         smearing = default_params["smearing"]
    101 
--> 102     pw_parameters = qeapp_wc.inputs.relax.base.pw.parameters.get_dict()
    103     if scf_kpoints_distance is None:
    104         scf_kpoints_distance = qeapp_wc.inputs.relax.base.kpoints_distance.value

/opt/conda/lib/python3.9/site-packages/aiida/orm/utils/managers.py in __getattr__(self, name)
    143             # Otherwise, the exception is not caught by `getattr` and is propagated, instead of returning the default.
    144             prefix = 'input' if self._incoming else 'output'
--> 145             raise NotExistentAttributeError(
    146                 f"Node<{self._node.pk}> does not have an {prefix} with link label '{name}'"
    147             ) from exception

NotExistentAttributeError: Node<1013> does not have an input with link label 'relax'
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNptWFtv67gR_iuB-7oyLPkSO2_bvC3O6abN2T0oimJBUbTMmCIZkrKjLM5_73Bm6CiLPvqjOPf5Zug_FxcVonZ28VD_tPBGpKML
w-Lhz4UI8qSTkmkMavHwn8Vu0-q0-Gmx-C98N6WTs3_cri7Wy8NyA4cfyN_qzb76rR1tGu-
evz7dfXX27leZ7ur7u3r3sGoeVru737493jWrpln8AJFCnkWvIqrWuhOVdFnxolnWywZEE-
ijGjsH8Gq5X65u8OsoQNGgog8qxny-gWu3cyPaLKmZ3wGsUsaiqJmGDJ_coOj7zzKq1wL_5cKrqq4unOVJaPv_v7jqrlcpVq2I5N
RquRI1fuEqr88CwB2Yx1AYXjGqawKMGlotAamXu-U2Izbq5pQGgxh7ZSft8NaOdHvf6RDxiw1mB5DBdWoevZzki6q8SCeEN6Qw9P
SzYVGhd7ap5PGos_GrEhf0BWw8LNf4c7Ky6pVVQSQXUHGN36WEdjQQFLz4d9Eqg2E4oL4Wki-FMaQTP8mQdyHF5XG0MjlnYmXCWE
khT4ojkX1qZZh8QjMatLU1Cj7h6KEko-1ZkTl4w53VCZVv0Ow2uGS0n1D5PV0ZB3_BK7k8IZn1AdDHrPrR2RQcWVrDUVaJNqGJWH
gNqpE3rxt2SaqQNEewya43m4Ky9hoN4jBD8DaYbHnsL7NqgCoLnUqoakWCAYkqVRbqRhj9TpaDNPpcDdoeHas40A0d5BhJ5z2GTR
otzwDsixH5N_SgPeq-OmpDVbOj23gWvbYWVWXDMdHSGRfEILiUdgjZTlA_rsieDFTc7tVJ2A7y06O_96QZdbr2BbAteMhSkhsD-l
AXLCfe9UH404Th2SzvMzxJU6yiMn1EtqLagkrN3nZCArdxGa0QSEIaEaOiqOwzpoCCuJKzIQfEjmNU3dtguFxqBIF2IN_EfIU1Oh
3PFbgBFBoTcVkJIBxBybWIrNGZzkZfzMz1gmJHc9WSG3G13OabCqhA2cT92iy3GDI1CG2qC-S-u3UeFT98C2Fy2ibyC79-k8pnY_
vgRs8RzaV4FDEJrykA1Ak588ZhZayZM46Qi49iXzM40pzIUd9jQWFiLvq9mF8jppQ1WLs1R-k0DsIeg1ZQB5hdKmndgeX6OLGTB4
SsoPDiB0NmBwhiNagkcvrQnO3y8yGMA6gbiVndQlyz_9BtwAcWGWgLN7aEDd5whzQEcDqgP4gVGcoMNyZt4oyt8hH4xgjfZ85HEf
d_ASv1lsBl1XEoUH6KnbC9gqzE2eB7UZ0ugc26ftH2RTSYEIrqi2upmAq9vkRnt-zLln9jDTAxrBkL6kgW8--YuUIwl6KgEfxSoY
KGh3TgiKqJ8m4nVNgb7oQCRxUuTLn7T5ISFjDUJNPG7Ow0tjyrZpJocqOnu09o5ac-d0KcDfDZ6c2AhltudvaRlxL5s75-DIAdA9
GZ4gONTyPCGYgLqDYU-l8hnKCjYK5KHuxZolFvuiOmz9y4ykKN68cwzmjgqzg7tiLLH8TQEnUC8dN5OHfuapndaoZG_yyOaqZsEM
kbx4xSxv8HWGkLFKtmgRqAf0ZbFgHUDU09fUymA0JBVcCSoTT7vtg1-IH4p2amGmKfCZ2pBDWMJulOSyoawqxIEdoSJVHobIuci6
vNisdbxrjaVkxvADkLuUjYsDv-LC-
qgiAaWVbFVOESoimsW_pSpbycvWHA9sjstjcXra5cWXgX8qfshccQ2uaSap07owPkt4W1gCZQs8aoOTGmUwk7lZIDZh1Ep-
YdW7CPPuIw41pBo5BmYENTxsPGl5JojZrtMV4MygiOMQOvnhqaf8NkjTPPM-AkUDgkseyBDeIwpDXWXlOqONd12avpG_SsYfn3S-
9iqvmgVESpJ6_evJK0kpDLvo8js2EOr4eFwagIe4riLsu89KSNcTkLB_bgSXPea0qy154WKJpP5XnCa20eDARDmU9UCMQo3nCmQD
8jUMvSDYNO5DQlywfY9NNJjbGaFV0RAoc-VdnXs06FhTA9MfM_KqRnj4-TdL5veKVtZlDVaivCND9JE4iGkRRnG6efWmARspiK7W
l61Md_fceY0h7oQWIUiQlkTciNj2DskCA5BoMzZ7PmTclPMFcSPyBqasanD_pseCl8mn75_m22wMBIFAmG3W0Nxtp8mr5Oz__8wu
Nljcg_xKPhuqOLv3pln5-_UEUTSfkpm8plzruanwCJ6Rb4e5b3DBtH5F6kuzh4YcorjnzDbyU-gRFZ9h4uFcLzVKuAd3sOUTEluR
cpBj8bQnmAi4l5iCW83wgcrfr3z1-_YNI3LOUdX2m3ZyK8AktjNNyiQb2OwEoENWRywW5PmRzH3fxgcMylvAyFo1wf9ve81mUCC2
Mmg-UkeA-FyB0-w0tZFkzaR-ioykdV2cnh3na5zxqi1FDjFTydgi1F2BDOjEepjkqdfeH-A-bwGdaY5lsQ8TSrAHiNjP62JB7yvE
MCydFc1avsQjzBLBhH3XHWcKuL-o0cpwEZrYa3kJutNtH3Zdep6SkMtfizyYvLVEZ1zh4ssiFzqJqTQEwBJlKVw7leH6j7MjwVWm
daAOYd81RnOkTLoEjzm2HiJxJBAV5Wgv-O4OdNggzeXtMUjHQKSnQeoiGT4VGBuCvZo5aECmZpxH7ptRuw_XdsVhA6GdpctkX2BK
-w_g_cJvM_L5H5Ip_BuxlmpgBO1bj_Zr3Z39EfoVCxN2YLL7DGxwOSQ7kmHCK-phxQyH8XsF5PM_6_aEglzCwcoA3Sd1Z0FUmeOt
cXJ3NirhLWLw5Pg9KuqsV3Iy9kDUHKwkoFrkUOZE1whNaAl-58RSAC_a7C-V2N_Wxxvp6UogCvaSWixa9qYSzGPDRmOeIjr4J2eW
25zd7V7Dja9hZo3rTQLHjppPJgzwC8Dm-rNBZVjuMkQvm3Jn_zrr2_7XU_fvwPnXN80Q==</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

### PR DESCRIPTION
**Pull request by unkcpz**
fixes #318 

@superstar54 We had a discussion about this, seems I didn't change these parts of code back to normal.

### CODE REVIEW

**Review by superstar54 — CHANGES_REQUESTED** [review]
There is a logic bug here.

If we run ``scf`` only, the ``pw_parameters`` will be ``None``.  Thus, the following code will raise a error.
```
    energy_cutoff_wfc = round(pw_parameters["SYSTEM"]["ecutwfc"])
```
Since we use ``parameters["relax_type"]=RealxType.NONE`` to run the ``scf`` calculation. So, no matter what kind of calculations we choose, there should always have a ``relax`` calculation. Therefore, line 33
```
run_relax = builder_parameters.get("relax_type") != "none"
```
needs change to:
```
run_relax = True
```

In file ``steps.py``, line 871,
```
        # skip relax sub-workflow only when RelaxType is NONE and has property calculated.
        if RelaxType(parameters["relax_type"]) is RelaxType.NONE and (
            parameters["run_bands"] or parameters["run_pdos"]
        ):
            builder.pop("relax")
```
The above code should be removed, to make sure there is a ``relax`` calculation.

@unkcpz What do you think?

**Comment by unkcpz** [comment]
Hi @superstar54, the issue is more complex. Please check the comment I add to the code. The problem all comes from us running SCF which is a non-relax calculation using the PwRelaxWorkChain.

**Review by superstar54 — CHANGES_REQUESTED** [review]
@unkcpz You are right. One quick solution would be:
Change 
```
    run_relax = builder_parameters.get("relax_type") != "none"
    run_bands = builder_parameters.get("run_bands")
    run_pdos = builder_parameters.get("run_pdos")
```
to:
```
    run_bands = builder_parameters.get("run_bands")
    run_pdos = builder_parameters.get("run_pdos")
    run_relax = not (builder_parameters.get("relax_type") == "none" & (run_relax or run_pdos))
```

**Comment by unkcpz** [comment]
@superstar54 thanks! I implement it by check if the `relax` port is in the workchain, please see my implementation, what you suggest has the advantage that the change all kept in one place, but to me, it is still very mind-binding. 
```
    # The run_relax variable is not same as if statement below.
    # the "relax" port is poped out to skip the real relaxiation
    # which is not the case of SCF, we use the relax workchain but with
    # relax_type set to none as SCF calculation.
    if "relax" in qeapp_wc.inputs:
        pw_parameters = qeapp_wc.inputs.relax.base.pw.parameters.get_dict()
        if scf_kpoints_distance is None:
            scf_kpoints_distance = qeapp_wc.inputs.relax.base.kpoints_distance.value
```

**Review by superstar54 — APPROVED** [review]
LGTM!

**Review by superstar54 — APPROVED** [review]

**Comment by unkcpz** [comment]
@superstar54 thanks millions!

**Pull request merged**
